### ISSUE TITLE
Dynamic SFX Client-Side Crash

### ISSUE THREAD

**Issue by SalvieMundi** [SalvieMundi/DefinitiveEditionVanillaPlus#24]
Null error on Echo.java line 175, FilterManager.java line 55

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 12/19/21, 11:55 AM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "com.mojang.datafixers.util.Pair.getSecond()" because "instance" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.65)
	at me.andre111.dynamicsf.filter.Echo.update(Echo.java:175)
	at me.andre111.dynamicsf.FilterManager.updateGlobal(FilterManager.java:55)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.client.MinecraftClient.handler$fjo000$onEndTick(MinecraftClient:18573)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1806)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1081)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.andre111.dynamicsf.filter.Echo.update(Echo.java:175)
	at me.andre111.dynamicsf.FilterManager.updateGlobal(FilterManager.java:55)

-- Affected level --
Details:
	All players: 2 total; [class_746['SalveMundiProd'/187, l='ClientWorld minecraft:overworld', x=280.12, y=64.00, z=272.01], class_745['Pachimarissa'/699, l='ClientWorld minecraft:overworld', x=284.50, y=63.00, z=281.07]]
	Chunk stats: Client Chunks (ImmPtl) 545
	Level dimension: minecraft:overworld
	Level spawn location: World: (230,65,208), Section: (at 6,1,0 in 14,4,13; chunk contains blocks 224,-64,208 to 239,319,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4869576 game time, 28123 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$cak000$onCrash(class_310.java:12099)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Fabric Mods, xali's+Potions+v0.1.zip, xali's+Enchanted+Books+v0.8.zip, Default, BedrockWaters.zip, CTM+Overhaul+Consistency++Edition+v1.0.zip, Charmonium.zip, Chests-Reimagined-v1-2.zip, Cloudier+Clouds.zip, Connected+Logs+1.16.3.zip, Connectibles.zip, ContinuityDefault.zip, ContinuityPaneGlassFix.zip, Dimensional+Bedrock+-+1.1.zip, EmbellishedStone-1.17.1.zip, Enchanted+Tools+v2.5.zip, Enchanted+Weapons+sv0.2.zip, NumberedHotbar.zip, Ore+Variants+v1.75.zip, RemasteredEnderDragon.zip, VanillaTweaks_r588102.zip, connected-textures-e2461.zip, xali's+Enhanced+Jungle+Wood+v1.2.zip, Furnaces-Reimagined-v1.zip, Pumpkins-Reimagined-v1.zip, fabric-copper-golem/copper_golem, Rainbow+XP+bar+and+ping+1.17.zip, copper_golem.zip, keyboard-sounds.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2345225440 bytes (2236 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 3.20
	Number of physical packages: 2
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2208
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9613
	Graphics card #1 name: ASPEED Graphics Family(WDDM)
	Graphics card #1 vendor: ASPEED (0x1a03)
	Graphics card #1 VRAM (MB): 16.00
	Graphics card #1 deviceId: 0x2000
	Graphics card #1 versionInfo: DriverVersion=9.0.10.110
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Memory slot #4 capacity (MB): 4096.00
	Memory slot #4 clockSpeed (GHz): 2.13
	Memory slot #4 type: DDR4
	Memory slot #5 capacity (MB): 4096.00
	Memory slot #5 clockSpeed (GHz): 2.13
	Memory slot #5 type: DDR4
	Memory slot #6 capacity (MB): 8192.00
	Memory slot #6 clockSpeed (GHz): 2.13
	Memory slot #6 type: DDR4
	Memory slot #7 capacity (MB): 4096.00
	Memory slot #7 clockSpeed (GHz): 2.13
	Memory slot #7 type: DDR4
	Virtual memory max (MB): 46736.43
	Virtual memory used (MB): 25625.72
	Swap memory total (MB): 5888.00
	Swap memory used (MB): 131.61
	JVM Flags: 22 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xms4G -Xmx4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		additionaladditions: Additional Additions 2.2.0
		adorn: Adorn 2.2.0+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.1
		advancementplaques: Advancement Plaques 1.4.1
		adventurez: AdventureZ 1.4.3
		alaskanativecraft: Alaska Native Craft 1.3.1
		ambientenvironment: Ambient Environment 6.0.22
		amecs: Amecs 1.3.4+mc.1.17
		amecsapi: Amecs API 1.1.5+mc21w16a
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		annotateddi: Annotated DI 2.0.3+1.17.1
		antiqueatlas: Antique Atlas 6.1.1-fabric-mc1.17.1
		aopalliance_aopalliance: aopalliance 1.0
		appletreesrev: Apple Trees Rev. 2.5
		aqupdcaracal: Caracal mob 1.17-1.3.2
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		architectury: Architectury 2.6.35
		artifacts: Artifacts 5.0.2+fabric
		audiooutput: AudioOutput 0.0.4
		autosmeltenchant: AutosmeltEnchant 1.1.0
		awesomedungeon: Awesome Dungeon 1.1.2
		axolotlitemfix: Axolotl Item Fix 1.1.3
		backslot: BackSlot 1.2.2
		backslotaddon: BackSlot Addon 1.0.7
		basicshields: Basic Shields [Fabric] 1.1.1-1.17.1
		battletowers: Battle Towers 3.4.1-1.17.1
		bclib: BCLib 0.3.1
		beaconoverhaul: Beacon Overhaul 1.4.2+1.17
		bedrockwaters: BedrockWaters 1.5.0+1.17.1
		beebuddy: Bee Buddies 1.1.3+1.17.1
		bendy-lib: Bendy api 2.0.4
		better_withered_mobs: Better Withered Mobs 1.6.1
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.11.0-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		betterthirdperson: Better Third Person 1.5.0
		biomeinfo: Biome Info 1.17-7
		bitsofbark: Bits of Bark 0.1
		blackstonetools: Blackstone Tools 2.0.0+1.17
		blockus: Blockus 2.2.10+1.17.1
		boatcontainer: BoatContainer 1.0.3
		bookworm: Bookworm Library 1.0.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.2-1.17.1
		bountiful: Bountiful 1.0.0
		brewable_experience: Brewable Experience 1.1.1
		caelus: Caelus API 0.0.18-1.17.1
		cameraoverhaul: Camera Overhaul 1.3.0-fabric-universal
		capybara: Capybara 1.0.0
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		castle_dungeons: Castle Dungeons 3.0-1.17-fabric
		cavebiomeapi: CaveBiomeAPI 1.2.2
		cdp: MapCrashFixer 1.0.0
		cem: Custom Entity Models 0.6.2
		chalk: Chalk 1.0.2
		charmonium: Charmonium 3.3.0
		chat_heads: Chat Heads 0.3.1+1.17.1
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		citresewn: CITResewn 0.8.1
		cleardespawn: Clear Despawn 1.17.1-1.1.2
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.1.40
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		collective-fabric: Collective (Fabric) 3.9
		columns: Columns 1.2.0
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_google_inject_guice: guice 5.0.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 0.0.7-1.17.1
		completeconfig: CompleteConfig 1.1.0
		consistency_plus: Consistency Plus 0.4.1-rc.3+1.17
		continuity: Continuity 1.0.2+1.17
		cr-arrows-info: Arrows Info 1.1.0+1.17
		craftablechainmail: Craftable Chainmail Armor 1.0.0
		croptopia: Croptopia 1.6.3
		croptosis: Croptosis 1.2.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.3.2
		customizableelytra: Customizable Elytra 1.5.1-1.17
		darkpaintings: Dark Paintings 4.0.2
		dawn: Dawn API 2.0.6
		deathcoords: Death Coords 1.0.1
		dehydration: Dehydration 1.2.5
		desolation: Desolation 1.2.0
		detailab: Detail Armor Bar 2.6.1+1.17.1-fabric
		disenchanter: Disenchanter 0.1.2
		dragondropselytra-fabric: Dragon Drops Elytra (Fabric) 1.4
		dragonloot: DragonLoot 1.0.9
		dualwielding: Dual Wielding 1.0.6
		dungeons_arise: When Dungeons Arise 2.1.49-fabric
		dynsfx: DynSFX 1.5.0
		ears: Ears 1.4.2
		earthtojavamobs: Earth2Java 1.7.3+1.17
		editsign: EditSign 2.2.4
		emotecraft: Emotecraft 2.1-SNAPSHOT-build.8
		enchant_giver: Enchant Giver 1.1.0
		endgoblintraders: End Goblin Traders 1.3.0
		endrem: End Remastered 4.1.0
		enhancedblockentities: Enhanced Block Entities 0.5+1.17
		entityculling: EntityCulling-Fabric 1.3.3
		environmentz: EnvironmentZ 1.1.7
		expandability: ExpandAbility 4.0.2
		explorerscompass: Explorer's Compass 1.17.1-2.0.2-fabric
		extra_enchants: Extra Enchants 0.1.4
		extrasounds: Extra Sounds 2.0.1+1.17
		fabric: Fabric API 0.41.0+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-copper-golem: Copper Golem 1.0.1+1.17.1
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.1+5847535018
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+5847535018
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.10+5847535018
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.4+5847535018
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.5+5847535018
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.0+5847535018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.6+5847535018
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.0+5847535018
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.0+5847535018
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+5847535018
		fabricloader: Fabric Loader 0.11.7
		fabricshieldlib: Fabric Shield Lib 1.4.5+1.17
		fading: Fading 1.3.0
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fastfurnace: FastFurnace 1.17-3.0
		fastopenlinksandfolders: FastOpenResourcePacks 1.0.0
		ferritecore: FerriteCore 3.1.0
		fiber: fiber 0.23.0-2
		fireplacelib: Fireplace Lib 6.0.7+1.17.1
		flonters: Flonters 1.2.1+1.17.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.29
		geodes: More Geodes 1.0.4
		glassdoor: Glass Doors 1.5.0-1.16
		go-fish: Go Fish 1.3.1-1.17.1
		gobber2: Gobber2 2.4.60
		goblintraders: Goblin Traders 1.3.0
		goosiklib: Goosik Lib 0.1.0
		goprone: GoProne 1.0
		graveyard: The Graveyard 2.1
		guardiansgalore: GuardiansGalore 1.17.1-2.1
		guild: Guild 0.3.4
		harvest_scythes: Harvest Scythes 2.1.0
		hookshot: Hookshot 22.0
		icarus: Icarus 1.3
		illuminations: Illuminations 1.8
		imm_ptl_core: Immersive Portals Core 0.34
		immersive_portals: Immersive Portals 0.34
		indium: Indium 1.0.1+mc1.17.1
		inventoryprofilesnext: Inventory Profiles Next 1.1.8
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		javax_inject_javax_inject: javax.inject 1
		just_end_anchor: Just An End Anchor 1.0.1
		kambrik: Kambrik 1.1.0
		kirin: Kirin UI 1.9.1
		koi: Koi Mod 1.0.1
		krypton: Krypton 0.1.4
		lakeside: Lakeside 1.1.0+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.1+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.5
		loud_leads: Loud Leads 1.0.1+mc1.17
		lovely_snails: Lovely Snails 1.0.3+1.17
		maelstrom_library: Maelstrom Library 1.2.2-1.17.1
		magiccombatwands: Magic Combat Wands 1.0.1
		malilib: MaLiLib 0.10.0-dev.26
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-data: Maybe data 1.0.1-1.17
		mcda: MC Dungeons Armors 1.7.15
		mcdar: MC Dungeons Artifacts 1.4.2
		mcdw: MC Dungeons Weapons 3.6.0
		mcsa: MC Story Mode Armor 2.3.2-1.17
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.17.1
		modmenu: Mod Menu 2.0.14
		morebannerfeatures: More Banner Features 1.1.1
		moreflowerpots: com.eternalhelldevs.moreflowerpots 2.0-SNAPSHOT
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		multipart_entities: MultipartEntities 1.1.3-1.17.1
		musketmod: Musket Mod 1.4.1
		mythic-mounts: Mythic Mounts 1.17.1-3.0
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nears: Nears 1.1.2
		netherroof: NetherRoofMod 1.0.2
		no_null_processors: No Null Processors - Fabric 1.0.0+1.17.1
		notenoughanimations: NotEnoughAnimations 1.4.0
		notenoughcrashes: Not Enough Crashes 3.3.0+1.17
		notforgotten: Not Forgotten 1.0.1
		now-playing: Now Playing 1.2.0
		npcvariety: NPC Variety 2.2.0
		nyfsquivers: Nyf's Quivers 0.2.6
		omega-config: OmegaConfig 1.0.8
		openloader: OpenLoader 3.0.1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		outvoted: Outvoted 2.0.14
		outvoted_new: Outvoted 1.5.0
		owo: oωo 0.3.2+1.17
		paradoxconfig: Paradox Config 0.5.1-beta
		particlerain: Particle Rain 1.5.0
		patchouli: Patchouli 1.17.1-59-FABRIC
		patternedglass: Patterned Glass 1.17-1.0.1
		pettable: Pettable 1.2.0
		physicsmod: Physics Mod 2.5.17
		pigsteel: Pigsteel Mod 1.6.6
		pitch-dark: Pitch Dark 2.0.0
		plushies: Plushie Mod 1.1
		polymorph: Polymorph 0.0.14-1.17.1
		presencefootsteps: Presence Footsteps 34.1.0
		pride: Pride Lib 1.1.0+1.17
		promenade: Promenade 2.1.2
		pugh_lib: Pugh Lib 1.1.6
		pugh_tools: Pugh Tools 1.0.5
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.34
		raisedclouds: Raised Clouds 1.0.0
		randore: Rand'Ore 1.3.1
		ratsmischief: Rat's Mischief 1.3.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reinfbarrel: Reinforced Barrels 1.0.4+1.17
		reinfchest: Reinforced Chests 1.0.4+1.17
		reinfcore: Reinforced Core 1.1.1+1.17
		repurposed_structures: Repurposed Structures 2.5.7+1.17.1
		reroll: Reroll 1.3.0-1.17.1
		ripplers: Ripplers 0.3.1
		riverredux: River Redux 0.2.0
		roughlyenoughitems: Roughly Enough Items 6.2.351
		secondchance: Second Chance 1.2.0
		sheepconsistency: Sheep Consistency 1.0.3
		shulkerutils: shulkerutils 1.0.4-1.17
		shwfox: Shadew's Foxes 1.1+fabric
		simple_backpack: SimpleBackpack 1.1.19
		skeletonhorsespawn-fabric: Skeleton Horse Spawn (Fabric) 1.9
		slimyfloor: Slimy Floor 1.17.1-1.2.0
		smoothboot: Smooth Boot 1.16.5-1.6.0
		snowpig: Snow Pig 1.0.0
		snowundertrees: Snow Under Trees 1.0.0
		sodium: Sodium 0.3.3+build.8
		solidxp: Solid Experience 1.0.0
		somnus: Somnus API 0.0.13-1.17.1
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.0+fabric.73f6d37
		starterkit-fabric: Starter Kit (Fabric) 2.6
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		statuseffecttimer: Status Effect Timer 1.0.3
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 1.1.0
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		strawgolem: Strawgolem 1.10-B5
		structure-helpers: Structure Helpers 3.2.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		things: Things 0.2.7
		thonkutil: ThonkUtil 1.2
		tooltipfix: ToolTip Fix 1.0.4-1.17.1
		transliterationlib: TRansliterationLib 1.2.2
		transportables: Transportables 1.0.6
		traverse: Traverse 4.0.0
		trinkets: Trinkets 3.0.4
		unlimiteddragoneggs: Unlimited Dragon Eggs 1.2.1
		untitledduckmod: Untitled Duck Mod 0.3.0
		upgradedshulkers: Upgraded Shulkers 1.1.1-1.17
		urns: Urns 1.0.1
		vanilla_degus: Vanilla Degus 1.2.4
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		villagernames: Villager Names 2.0.1
		visuality: Visuality 0.1.3
		voicechat: Simple Voice Chat 1.17.1-2.1.28
		vorpal-enchantment: Vorpal Enchantment 1.0.0
		waig: Where Am I Going 1.0.0
		waterdripsound: Drip Sounds 1.17-0.2.2
		waystones: Waystones 2.2.2
		windchimes: Windchimes 1.2.0
		wmitaf: WMITAF 1.2.0
		wolveswitharmor: Wolves With Armor 1.6.1-1.17.1
		woods_and_mires: Woods and Mires 1.1.1+1.17
		wthit: wthit 3.11.2
		xlpackets: XLPackets 2.0-1.17
		yungsapi: YUNG's API 1.17-Fabric-19
		zombiehorsespawn-fabric: Zombie Horse Spawn (Fabric) 3.0
	Launched Version: fabric-loader-0.11.7-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 496.13, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, openloader/resources/xali's+Potions+v0.1.zip (incompatible), openloader/resources/xali's+Enchanted+Books+v0.8.zip, vanilla, openloader/resources/BedrockWaters.zip, openloader/resources/CTM+Overhaul+Consistency++Edition+v1.0.zip, openloader/resources/Charmonium.zip, openloader/resources/Chests-Reimagined-v1-2.zip, openloader/resources/Cloudier+Clouds.zip, openloader/resources/Connected+Logs+1.16.3.zip (incompatible), openloader/resources/Connectibles.zip, openloader/resources/ContinuityDefault.zip, openloader/resources/ContinuityPaneGlassFix.zip, openloader/resources/Dimensional+Bedrock+-+1.1.zip, openloader/resources/EmbellishedStone-1.17.1.zip, openloader/resources/Enchanted+Tools+v2.5.zip, openloader/resources/Enchanted+Weapons+sv0.2.zip, openloader/resources/NumberedHotbar.zip, openloader/resources/Ore+Variants+v1.75.zip, openloader/resources/RemasteredEnderDragon.zip, openloader/resources/VanillaTweaks_r588102.zip, openloader/resources/connected-textures-e2461.zip, openloader/resources/xali's+Enhanced+Jungle+Wood+v1.2.zip, openloader/resources/Furnaces-Reimagined-v1.zip, openloader/resources/Pumpkins-Reimagined-v1.zip
	Current Language: English (US)
	CPU: 32x Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0

**Comment by SalvieMundi** [comment]
To remind myself later:

This class, line 175, need to check if instance == null before proceeding

https://gitlab.com/mikenrafter1/mc-dyn-sfx/-/blob/main/src/main/java/me/andre111/dynamicsf/filter/Echo.java

**Comment by SalvieMundi** [comment]
Trying fix on my own installation before moving into the repository

**Comment by SalvieMundi** [comment]
fixed on my personal server. will commit up to github shortly
