### ISSUE TITLE
better animal crash

### ISSUE THREAD

**Issue by pachimarissa** [SalvieMundi/DefinitiveEditionVanillaPlus#45]
i pet a badge
[crash-2021-12-29_21.23.21-client.txt](https://github.com/SalvieMundi/DefinitiveEditionVanillaPlus/files/7791275/crash-2021-12-29_21.23.21-client.txt)
r

**Comment by SalvieMundi** [comment]
Appears to be due to a reindeer spawning in:

java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because "v" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.65)
	at dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer$CustomConfigurationHolder.getBooleanHolder(EntityTypeContainer.java:421)
	at dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer$CustomConfigurationHolder.getBoolean(EntityTypeContainer.java:391)
	at dev.itsmeow.betteranimalsplus.common.entity.EntityReindeer.tickMovement(EntityReindeer.java:481)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2346)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:339)
	at dev.itsmeow.betteranimalsplus.common.entity.EntityReindeer.tick(EntityReindeer.java:526)
	at net.minecraft.client.world.ClientWorld.tickEntity(ClientWorld:179)
	at net.minecraft.world.World.tickEntity(World:483)
	at net.minecraft.client.world.ClientWorld.method_32124(ClientWorld:167)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld:163)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1750)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1081)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.MinecraftClient.handler$cao000$afterCrashHandled(MinecraftClient:12091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.MinecraftClient.handler$cao000$afterCrashHandled(MinecraftClient:12091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.MinecraftClient.handler$cao000$afterCrashHandled(MinecraftClient:12091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by SalvieMundi** [comment]
will be fixed in 1.0.7a
