### ISSUE TITLE
Shit Tons of Server Crashes

### ISSUE THREAD

**Issue by SalvieMundi** [SalvieMundi/DefinitiveEditionVanillaPlus#48]
Yet Another Server Crash Mod version 9000+
[logs.zip](https://github.com/SalvieMundi/DefinitiveEditionVanillaPlus/files/7800322/logs.zip)

**Comment by SalvieMundi** [comment]
Ticking entity bug with Better Animals Plus tarantula projectile:

java.lang.NoClassDefFoundError: net/minecraft/class_638
	at dev.architectury.networking.fabric.NetworkManagerImpl.createAddEntityPacket(NetworkManagerImpl.java:139)
	at dev.architectury.networking.NetworkManager.createAddEntityPacket(NetworkManager.java)
	at dev.itsmeow.betteranimalsplus.common.entity.projectile.EntityTarantulaHair.createSpawnPacket(EntityTarantulaHair.java:60)
	at net.minecraft.server.network.EntityTrackerEntry.sendPackets(EntityTrackerEntry:226)
	at net.minecraft.server.network.EntityTrackerEntry.mddf18e6$lambda$startTracking$1$0(EntityTrackerEntry:2567)
	at qouteall.imm_ptl.core.network.IPCommonNetwork.withForceRedirect(IPCommonNetwork.java:31)
	at net.minecraft.server.network.EntityTrackerEntry.startTracking(EntityTrackerEntry:2563)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage$EntityTracker.updateEntityTrackingStatus(ThreadedAnvilChunkStorage:1425)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage$EntityTracker.updateTrackedStatus(ThreadedAnvilChunkStorage:1388)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.loadEntity(ThreadedAnvilChunkStorage:991)
	at net.minecraft.server.world.ServerChunkManager.loadEntity(ServerChunkManager:460)
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.startTracking(ServerWorld:1426)
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.startTracking(ServerWorld:1404)
	at net.minecraft.server.world.ServerEntityManager.startTracking(ServerEntityManager:210)
	at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:180)
	at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:161)
	at net.minecraft.server.world.ServerWorld.addEntity(ServerWorld:808)
	at net.minecraft.server.world.ServerWorld.spawnEntity(ServerWorld:759)
	at dev.itsmeow.betteranimalsplus.common.entity.EntityTarantula.attack(EntityTarantula.java:62)
	at net.minecraft.entity.ai.goal.ProjectileAttackGoal.tick(ProjectileAttackGoal:89)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.tick(PrioritizedGoal:55)
	at net.minecraft.entity.ai.goal.GoalSelector.tickGoals(GoalSelector:1157)
	at net.minecraft.entity.ai.goal.GoalSelector.tick(GoalSelector:1056)
	at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity:733)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2601)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:539)
	at net.minecraft.entity.mob.HostileEntity.tickMovement(HostileEntity:43)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2346)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:339)
	at net.minecraft.entity.mob.SpiderEntity.tick(SpiderEntity:88)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:655)
	at net.minecraft.world.World.tickEntity(World:483)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:417)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:392)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:891)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:335)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:831)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 41 more

**Comment by Tigerboy007** [comment]
I also made the mistake of talking to a tarantula...

**Comment by SalvieMundi** [comment]
will be fixed in 1.0.7a
